# Generated by Django 4.2 on 2024-10-21 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_resized.forms


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField(blank=True)),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, default='../default_post_f67djn', force_format=None, keep_meta=True, quality=75, scale=None, size=[300, 300], upload_to='posts/')),
                ('tags', models.CharField(choices=[('Mindfulness', 'Mindfulness'), ('Motivation', 'Motivation'), ('Personal Growth', 'Personal Growth'), ('Time Management', 'Time Management'), ('Productivity', 'Productivity'), ('Goal Setting', 'Goal Setting'), ('Career Development', 'Career Development'), ('Leadership', 'Leadership')], default='Personal Growth', max_length=100)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
