# Generated by Django 4.2 on 2024-10-21 14:01

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='../default_post_f67djn', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[300, 300], upload_to='posts/'),
        ),
    ]
