# Generated by Django 4.2 on 2024-10-17 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(choices=[('Mindfulness', 'Mindfulness'), ('Motivation', 'Motivation'), ('Personal Growth', 'Personal Growth'), ('Time Management', 'Time Management'), ('Productivity', 'Productivity'), ('Goal Setting', 'Goal Setting'), ('Career Development', 'Career Development'), ('Leadership', 'Leadership')], default='Personal Growth', max_length=100),
        ),
    ]
